### ISSUE TITLE
The collection of videos in CinePile

### ISSUE THREAD

**Issue by qijimrc** [mfarre/Video-LLaVA-7B-hf-CinePile#2]
Hi, thank you for your great work. I wonder how did you obtain the raw videos in CinePile as they only provided the annotations in Huggingface. Thank you very much.

**Comment by mfarre** [comment]
hello @qijimrc unfortunately I had to get the videos on my own given the YouTube video ids in the dataset.

If you are interested in multimodal video datasets easier to get access to we might get some news in the next month :-)
